#  casks
#tap 'caskroom/homebrew-cask' || true
cask_args appdir: '/Applications'

cask 'google-chrome'
cask 'flux'
cask 'steam'
cask 'spotify'
cask 'love'
cask 'vlc'
cask 'kitty'
cask 'google-cloud-sdk'

# ai
brew 'aider'
brew 'aichat'

# Containers
brew 'docker'
brew 'colima'

# vcs
brew 'gh'
brew 'git'
brew 'git-lfs'

# Vis
brew 'graphicsmagick'
brew 'imagemagick'
brew 'graphviz'

# editor
brew 'neovim'

# shell
brew 'zsh'
brew 'zsh-completions'
brew 'zoxide'
brew 'zsh-syntax-highlighting'
brew 'antidote'
brew 'pure'
brew 'fzf'

# wm
tap 'koekeishiya/formulae'
brew 'yabai'
brew 'skhd'

# python
brew 'poetry'

# search
brew 'the_silver_searcher'
brew 'ripgrep'

# lua
brew 'luajit'
brew 'luarocks'

# utils
brew 'zip'
brew 'eza'
brew 'htop'
brew 'pandoc'
brew 'cloc'
brew 'wget'

# js/npm
brew 'node'

# k8s
brew 'kubectl'
brew 'minikube'

# auth
brew 'gpg'
brew 'pinentry-mac'
