set nocompatible
syntax enable
filetype plugin indent on

set nohlsearch
set mouse=

" Timeout (faster Esc)
set timeoutlen=1000
set ttimeoutlen=10

" Disable ex-mode and macro recording
map q: <Nop>
nnoremap Q <nop>
map q <Nop>

" Tabs
set smartindent
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

" UI
set number
set showcmd
set cursorline
set path+=**
set wildmenu
set wildmode=list:longest,full
set lazyredraw
set showmatch
set ruler

" Search
set incsearch
set ignorecase
set smartcase

" Backups
set backup
set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set backupskip=/tmp/*,/private/tmp/*
set directory=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set writebackup

" General
set autowrite
set autoindent
set autoread
set undolevels=1000
set visualbell
set splitbelow
set splitright

" Move by visual line
nnoremap j gj
nnoremap k gk

" Disable arrow keys
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>
imap <up> <nop>
imap <down> <nop>
imap <left> <nop>
imap <right> <nop>

" netrw
let g:netrw_banner = 0
let g:netrw_liststyle = 3

" Writing mode
function! Writing()
    setlocal spell spelllang=en_gb
    setlocal wrap linebreak
    setlocal softtabstop=4 tabstop=4 shiftwidth=4
    setlocal textwidth=80 wrapmargin=2
    syntax match AcronymNoSpell '\<\(\u\|\d\)\{3,}s\?\>' contains=@NoSpell
    syntax match UrlNoSpell '\w\+:\/\/[^[:space:]]\+' contains=@NoSpell
    syn match doubleWord "\c\<\(\a\+\)\_s\+\1\>"
    hi def link doubleWord Error
endfunction

au BufNewFile,BufFilePre,BufRead *.md set filetype=markdown
autocmd FileType gitcommit  call Writing()
autocmd FileType markdown   call Writing()
autocmd FileType wiki       call Writing()
autocmd FileType tex        call Writing()

" Strip trailing whitespace on save
autocmd FileType c,cpp,lua,md,tex,python autocmd BufWritePre <buffer> %s/\s\+$//e
