# Path to oh-my-zsh 
fpath=(~/.zsh $fpath)
export ZSH=$HOME/.oh-my-zsh

## Plugins via oh-my-zsh
plugins=(cp macos ag)
#Look in ~/.oh-my-zsh/themes/
ZSH_THEME="honukai"
#Timestamp format
HIST_STAMPS="dd.mm.yyyy"


source $ZSH/oh-my-zsh.sh
source ~/.shellrc

alias vim="nvim"
alias vi="nvim"
alias v="nvim"
alias ls="eza"

# gcloud sdk
source "$(brew --prefix)/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc"
source "$(brew --prefix)/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc"

#GitHub signed commits
export GPG_TTY=$(tty)
gpgconf --launch gpg-agent

export PATH="$HOME/.poetry/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
eval "$(/opt/homebrew/bin/brew shellenv)"
