# Path to oh-my-zsh 
fpath=(~/.zsh $fpath)
export ZSH=$HOME/.oh-my-zsh

## Plugins via oh-my-zsh
plugins=(cp macos ag)
#Look in ~/.oh-my-zsh/themes/
ZSH_THEME="honukai"
#Timestamp format
HIST_STAMPS="dd.mm.yyyy"


source $ZSH/oh-my-zsh.sh
source ~/.shellrc

alias vim="nvim"
alias vi="nvim"
alias v="nvim"

# gcloud sdk
source "$(brew --prefix)/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc"
source "$(brew --prefix)/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc"

#GitHub signed commits
export GPG_TTY=$(tty)
gpgconf --launch gpg-agent

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/homebrew/Caskroom/miniconda/base/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh" ]; then
        . "/opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh"
    else
        export PATH="/opt/homebrew/Caskroom/miniconda/base/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<


export PATH="$HOME/.poetry/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
eval "$(/opt/homebrew/bin/brew shellenv)"
